[[redirects]]
  from = "*"
  to = "https://kungfutech.edu.vn/fpt"
[[redirects]]
  from = "/"
  to = "https://kungfutech.edu.vn/fpt"

[[redirects]]
  from = "/*"
  to = "https://kungfutech.edu.vn/fpt"
